name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "keyboards/keebio/iris/keymaps/loquillo/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Compile
        shell: bash
        run: qmk compile -kb keebio/iris/rev4 -km loquillo
      - uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: .build/keebio_iris_rev4_loquillo.hex

        