name: Build

on:
  push:
    - "github/workflows/build.yml"
    - "keyboards/keebio/iris/rev4/**"

jobs:
  build:
    run-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile
        shell: bash
        run: qmk compile kb keebio/iris/rev4 -km default

        